USE ESTUDO_2023

-- VISUALIZA A TABELAS

SELECT * FROM TB_FASES

--  DELETAR A LINHA 7 E 8

BEGIN TRAN
DELETE FROM TB_FASES WHERE ID_FASE IN (7,8)

--  AS LINHAS FIRCARAM DESORDENADAS, VAMOS REORDERNAR COM O A UTILIZACAO DA CTE E O ROW_NUMBER()


WITH CTE AS (
    SELECT ID_FASE, NR_FASE, DS_FASE, FL_RECURSO,
           ROW_NUMBER() OVER (ORDER BY NR_FASE) AS NOVA_ORDENACAO
    FROM TB_FASES
)
UPDATE CTE SET NR_FASE = NOVA_ORDENACAO;

-- 

SELECT * FROM TB_FASES
ROLLBACK
